class MyData {
  static numbers = [
    { n: 0, e: "zero", s: "cero" },
    { n: 1, e: "one", s: "uno" },
    { n: 2, e: "two", s: "dos" },
    { n: 3, e: "three", s: "tres" },
    { n: 4, e: "four", s: "cuatro" },
    { n: 5, e: "five", s: "cinco" },
    { n: 6, e: "six", s: "seis" },
    { n: 7, e: "seven", s: "siete" },
    { n: 8, e: "eight", s: "ocho" },
    { n: 9, e: "nine", s: "nueve" },
    { n: 10, e: "ten", s: "diez" },
    { n: 11, e: "eleven", s: "once" },
    { n: 12, e: "twelve", s: "doce" },
    { n: 13, e: "thirteen", s: "trece" },
    { n: 14, e: "fourteen", s: "catorce" },
    { n: 15, e: "fifteen", s: "quince" },
    { n: 16, e: "sixteen", s: "dieciseis" },
    { n: 17, e: "seventeen", s: "diecisiete" },
    { n: 18, e: "eighteen", s: "dieciocho" },
    { n: 19, e: "nineteen", s: "diecinueve" },
    { n: 20, e: "twenty", s: "veinte" },
    { n: 21, e: "twenty one", s: "veintiuno" },
    { n: 22, e: "twenty two", s: "veintidos" },
    { n: 23, e: "twenty three", s: "veintitres" },
    { n: 24, e: "twenty four", s: "veinticuatro" },
    { n: 25, e: "twenty five", s: "veinticinco" },
    { n: 26, e: "twenty six", s: "veintiseis" },
    { n: 27, e: "twenty seven", s: "veintisiete" },
    { n: 28, e: "twenty eight", s: "veintiocho" },
    { n: 29, e: "twenty nine", s: "veintinueve" },
    { n: 30, e: "thirty", s: "treinta" },
    { n: 31, e: "thirty one", s: "treinta y uno" },
    { n: 32, e: "thirty two", s: "treinta y dos" },
    { n: 33, e: "thirty three", s: "treinta y tres" },
    { n: 34, e: "thirty four", s: "treinta y cuatro" },
    { n: 35, e: "thirty five", s: "treinta y cinco" },
    { n: 36, e: "thirty six", s: "treinta y seis" },
    { n: 37, e: "thirty seven", s: "treinta y siete" },
    { n: 38, e: "thirty eight", s: "treinta y ocho" },
    { n: 39, e: "thirty nine", s: "treinta y nueve" },
    { n: 40, e: "forty", s: "cuarenta" },
    { n: 41, e: "forty one", s: "cuarenta y uno" },
    { n: 42, e: "forty two", s: "cuarenta y dos" },
    { n: 43, e: "forty three", s: "cuarenta y tres" },
    { n: 44, e: "forty four", s: "cuarenta y cuatro" },
    { n: 45, e: "forty five", s: "cuarenta y cinco" },
    { n: 46, e: "forty six", s: "cuarenta y seis" },
    { n: 47, e: "forty seven", s: "cuarenta y siete" },
    { n: 48, e: "forty eight", s: "cuarenta y ocho" },
    { n: 49, e: "forty nine", s: "cuarenta y nueve" },
    { n: 50, e: "fifty", s: "cincuenta" },
    { n: 51, e: "fifty one", s: "cincuenta y uno" },
    { n: 52, e: "fifty two", s: "cincuenta y dos" },
    { n: 53, e: "fifty three", s: "cincuenta y tres" },
    { n: 54, e: "fifty four", s: "cincuenta y cuatro" },
    { n: 55, e: "fifty five", s: "cincuenta y cinco" },
    { n: 56, e: "fifty six", s: "cincuenta y seis" },
    { n: 57, e: "fifty seven", s: "cincuenta y siete" },
    { n: 58, e: "fifty eight", s: "cincuenta y ocho" },
    { n: 59, e: "fifty nine", s: "cincuenta y nueve" },
    { n: 60, e: "sixty", s: "sesenta" },
    { n: 61, e: "sixty one", s: "sesenta y uno" },
    { n: 62, e: "sixty two", s: "sesenta y dos" },
    { n: 63, e: "sixty three", s: "sesenta y tres" },
    { n: 64, e: "sixty four", s: "sesenta y cuatro" },
    { n: 65, e: "sixty five", s: "sesenta y cinco" },
    { n: 66, e: "sixty six", s: "sesenta y seis" },
    { n: 67, e: "sixty seven", s: "sesenta y siete" },
    { n: 68, e: "sixty eight", s: "sesenta y ocho" },
    { n: 69, e: "sixty nine", s: "sesenta y nueve" },
    { n: 70, e: "seventy", s: "setenta" },
    { n: 71, e: "seventy one", s: "setenta y uno" },
    { n: 72, e: "seventy two", s: "setenta y dos" },
    { n: 73, e: "seventy three", s: "setenta y tres" },
    { n: 74, e: "seventy four", s: "setenta y cuatro" },
    { n: 75, e: "seventy five", s: "setenta y cinco" },
    { n: 76, e: "seventy six", s: "setenta y seis" },
    { n: 77, e: "seventy seven", s: "setenta y siete" },
    { n: 78, e: "seventy eight", s: "setenta y ocho" },
    { n: 79, e: "seventy nine", s: "setenta y nueve" },
    { n: 80, e: "eighty", s: "ochenta" },
    { n: 81, e: "eighty one", s: "ochenta y uno" },
    { n: 82, e: "eighty two", s: "ochenta y dos" },
    { n: 83, e: "eighty three", s: "ochenta y tres" },
    { n: 84, e: "eighty four", s: "ochenta y cuatro" },
    { n: 85, e: "eighty five", s: "ochenta y cinco" },
    { n: 86, e: "eighty six", s: "ochenta y seis" },
    { n: 87, e: "eighty seven", s: "ochenta y siete" },
    { n: 88, e: "eighty eight", s: "ochenta y ocho" },
    { n: 89, e: "eighty nine", s: "ochenta y nueve" },
    { n: 90, e: "ninety", s: "noventa" },
    { n: 91, e: "ninety one", s: "noventa y uno" },
    { n: 92, e: "ninety two", s: "noventa y dos" },
    { n: 93, e: "ninety three", s: "noventa y tres" },
    { n: 94, e: "ninety four", s: "noventa y cuatro" },
    { n: 95, e: "ninety five", s: "noventa y cinco" },
    { n: 96, e: "ninety six", s: "noventa y seis" },
    { n: 97, e: "ninety seven", s: "noventa y siete" },
    { n: 98, e: "ninety eight", s: "noventa y ocho" },
    { n: 99, e: "ninety nine", s: "noventa y nueve" },
    { n: 100, e: "hundred", s: "cien" },
  ];
  static words = [
    { n: 0, e: "hello", s: "hola" },
    { n: 1, e: "yes", s: "si" },
    { n: 2, e: "no", s: "no" },
    { n: 3, e: "I", s: "yo" },
    { n: 4, e: "you", s: "tu" },
    { n: 5, e: "I'm", s: "soy" },
    { n: 6, e: "he", s: "el" },
    { n: 7, e: "she", s: "ella" },
    { n: 8, e: "old", s: "viejo" },
    { n: 9, e: "young", s: "joven" },
    { n: 10, e: "please", s: "por favor" },
    { n: 11, e: "thank you", s: "gracias" },
    { n: 12, e: "excuse me", s: "disculpe" },
    { n: 13, e: "where", s: "donde" },
    { n: 14, e: "who", s: "quien" },
    { n: 15, e: "what", s: "que" },
    { n: 16, e: "how", s: "como" },
    { n: 17, e: "why", s: "por que" },
    { n: 18, e: "my", s: "mi" },
    { n: 19, e: "name", s: "nombre" },
    { n: 20, e: "is", s: "es" },
    { n: 21, e: "John", s: "John" },
    { n: 22, e: "from", s: "de" },
    { n: 23, e: "England", s: "Inglaterra" },
    { n: 24, e: "are", s: "eres" },
  ];
  static sentences = [
    {
      n: 0,
      e: "Hello my name is John",
      s: "Hola, mi nombre es John",
      w: [0, 18, 19, 20, 21],
    },
    { n: 1, e: "Where are you from", s: "de dónde eres", w: [22, 13, 24] },
    { n: 2, e: "i'm from England", s: "Soy de Inglaterra", w: [5, 22, 23] },
  ];
}
